name: lardo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#c70011'
    - '#f9e9cb'
    - '#b29162'
    - '#005e66'
  brandStrength: 0.3170286782551557
  lightness: 0.8487007608637214
  saturation: 0.27106885029934347
  rhythmicContrast: 0.26356279384344816
purpose: []
